### ISSUE TITLE
npm ERR - unable to resolve dependency tree

### ISSUE THREAD

**Issue by HMonica** [id1945/ngx-qrcode-styling#10]
When I try to run: npm i ngx-qrcode-styling, I get the following error: 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree

npm ERR! Found: @angular/common@14.2.8
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.0" from the root project

npm ERR! Could not resolve dependency:
npm ERR! node_modules/ngx-qrcode-styling
npm ERR!   ngx-qrcode-styling@"*" from the root project

env: Angular CLI: 14.2.3、node v18.7.0、npm  8.15.0

**Comment by id1945** [comment]
I have updated support versions. You can update and use it :hugs:

<table>
  <tr>
    <th colspan="2">Support versions</th>
  </tr>
  <tr>
    <td>Angular 15</td>
    <td>1.2.1</td>
  </tr>
  <tr>
    <td>Angular 14</td>
    <td>1.2.0</td>
  </tr>
  <tr>
    <td>Angular 9</td>
    <td>1.1.9</td>
  </tr>
</table>
