### ISSUE TITLE
is this compatible to angular 13 ?

### ISSUE THREAD

**Issue by skandula106** [id1945/ngx-qrcode-styling#11]
In your readme.md showing like this 

**Support versions**
Angular 9 | 1.1.0
Angular 8 | 1.0.13

But current version 1.17 i want to use this in Angular 13

**Comment by id1945** [comment]
Version 1.1.7 still working  with Angular 13 
Please check it =>  https://stackblitz.com/edit/angular-13-ngx-qrcode-styling

**Comment by skandula106** [comment]
./node_modules/ngx-qrcode-styling/fesm2020/ngx-qrcode-styling.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/var/lib/jenkins/workspace/******/node_modules/ngx-qrcode-styling/fesm2020/ngx-qrcode-styling.mjs: This application depends upon a library published using Angular version 15.0.1, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.

Giving error while giving build via Jenkins currently we are using angular 13 and ngx-qrcode Version is 1.1.7 dev is working fine

**Comment by Moiz-5A4** [comment]
This application depends upon a library published using Angular version 15.0.1, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.


Facing above  issue with JIT compilation 

@id1945 can you please suggest stable version for angular 13 version

**Comment by id1945** [comment]
@Moiz-5A4 Okay I will release new version exclusive for Angular 13. :+1:

**Comment by Moiz-5A4** [comment]
![20221129_034744](https://user-images.githubusercontent.com/77195485/204392788-33c21a5a-191f-4562-b466-0c11f4a4cb74.jpg)

I have installed it but getting above image error.

**Comment by Moiz-5A4** [comment]
npm ERR! 
npm ERR! ssh: Could not resolve hostname github.com: Name or service not known
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

@id1945 facing above error when i trying to install the package.

**Comment by id1945** [comment]
@Moiz-5A4 You could install with npm below.
```
npm i https://github.com/id1945/ngx-qrcode-styling/archive/refs/tags/1.1.8-rtm-13.tar.gz
```

**Comment by Moiz-5A4** [comment]
npm ERR! code ENOTFOUND 
npm ERR! errno ENOTFOUND
npm ERR! network request to https://github.com/id1945/ngx-qrcode-styling/archive/refs/tags/1.1.8-rtm-13.tar.gz failed, reason: getaddrinfo ENOTFOUND github.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'



@id1945  facing above issue while running npm i https://github.com/id1945/ngx-qrcode-styling/archive/refs/tags/1.1.8-rtm-13.tar.gz

**Comment by id1945** [comment]
@Moiz-5A4 This problem is coming from your internet network.

**Comment by Moiz-5A4** [comment]
Ok No problem Thanks for your assistance @id1945
