### ISSUE TITLE
Non compatible Angular 14?

### ISSUE THREAD

**Issue by jesuscano80** [id1945/ngx-qrcode-styling#12]
Error importing module

node version: v14.15.5

@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core              12.2.13
@angular-devkit/schematics   12.2.13
@angular/cdk                          12.2.13
@angular/cli                           14.2.10
@schematics/angular             12.2.13
rxjs                            6.6.7
typescript                      4.8.4

import { NgxQrcodeStylingModule } from 'ngx-qrcode-styling';

@NgModule({
  imports: [
    NgxQrcodeStylingModule,
  ...
  ]
})

Error: node_modules/ngx-qrcode-styling/lib/ngx-qrcode-styling.component.d.ts:138:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

138     static ɵcmp: i0.ɵɵComponentDeclaration<NgxQrcodeStylingComponent, "ngx-qrcode-styling", never, { "config": "config"; "template": "template"; "type": "type"; "shape": "shape"; "width": "width"; "height": "height"; "margin": "margin"; "data": "data"; "image": "image"; "scale": "scale"; "rotate": "rotate"; "frameOptions": "frameOptions"; "qrOptions": "qrOptions"; "imageOptions": "imageOptions"; "dotsOptions": "dotsOptions"; "cornersSquareOptions": "cornersSquareOptions"; "cornersDotOptions": "cornersDotOptions"; "backgroundOptions": "backgroundOptions"; }, {}, never, ["*"], false, never>;

**Comment by id1945** [comment]
I have updated support versions. You can update and use it :hugs:

<table>
  <tr>
    <th colspan="2">Support versions</th>
  </tr>
  <tr>
    <td>Angular 15</td>
    <td>1.2.1</td>
  </tr>
  <tr>
    <td>Angular 14</td>
    <td>1.2.0</td>
  </tr>
  <tr>
    <td>Angular 9</td>
    <td>1.1.9</td>
  </tr>
  <tr>
    <td>Angular 8</td>
    <td>1.0.13</td>
  </tr>
</table>

**Comment by jesuscano80** [comment]
Thank you!
