### ISSUE TITLE
Canvas dataURL base64 image after qr code creation

### ISSUE THREAD

**Issue by samsonkumawong** [id1945/ngx-qrcode-styling#13]
Feature request:  Callback to return the canvas's base64 dataURL after the qr code was created

If the canvas context toDataURL is called, it shows a blank image instead, which means the canvas data was not initiated. I was able to get the canvas dataURL but this only triggers after a setTimeout for a certain time (e.g. 100ms).

Will there be an observable that returns the data:image/png;base64... upon the creation of the canvas without using setTimeout() for a certain time.

**Comment by id1945** [comment]
@samsonkumawong Can you demo on stackblitz ?

**Comment by samsonkumawong** [comment]
> @samsonkumawong Can you demo on stackblitz ?

Demo:
https://stackblitz.com/edit/angular-ngx-qrcode-styling-17pqhx?file=src/app/app.component.ts

**Comment by id1945** [comment]
@samsonkumawong 
Please use hidden instead of *ngIf

```html
<div [hidden]="shouldShowQRCode">
  <ngx-qrcode-styling #qrcode id="test-qr-code"></ngx-qrcode-styling>
</div>
```
