### ISSUE TITLE
Sử dụng trong angular với server side rendering

### ISSUE THREAD

**Issue by GinCanhViet** [id1945/ngx-qrcode-styling#7]
Chào bạn,
Ngồi đọc code trong cái lib của bạn học hỏi được rất nhiều.
Great work!!!

Cho mình hỏi là có cách nào import kiểu CommonJs để sử dụng khi bật SSR trong angular hay ko?
Thay vì:
`import { Options, QrCodeStylingModule  } from 'src/libs/ngx-qrcode-styling';`
Thì có thể:
`const { Options, QrCodeStylingModule  } = require('src/libs/ngx-qrcode-styling');`
Hoặc có cách xử lí khác.

Vì nếu sử dụng như bình thường thì lib này không tương thích với SSR.

**Comment by id1945** [comment]
@GinCanhViet Bạn có thể tạo video và bật network để mình xem được không?

**Comment by GinCanhViet** [comment]
@id1945 ý bạn là cần xem lỗi hả

**Comment by GinCanhViet** [comment]
1. Tạo prj: `ng new SsrTest --ssr`
2. `npm i ngx-qrcode-styling --save`
3. `ng serve  -o`
Báo lỗi: **self is not defined**
![image](https://github.com/id1945/ngx-qrcode-styling/assets/22634754/0c6c53ed-3814-434c-a65b-8785640081d8)

**Comment by GinCanhViet** [comment]
Nếu mà tắt ssr đi thì sẽ chạy bth
Trong `angular.json`

```
            "prerender": false,
            "ssr": false
```

**Comment by GinCanhViet** [comment]
![image](https://github.com/id1945/ngx-qrcode-styling/assets/22634754/04764a7e-6dc3-47a4-a729-eb8f95327344)


![image](https://github.com/id1945/ngx-qrcode-styling/assets/22634754/8c6557d1-09a5-4261-82cf-e1a8c1a5f6ae)

**Comment by GinCanhViet** [comment]
Mình đính kèm đây luôn cho tiện nếu bạn cần
[SsrTest.zip](https://github.com/user-attachments/files/15593461/SsrTest.zip)

**Comment by id1945** [comment]
> 1. Tạo prj: `ng new SsrTest --ssr`
> 2. `npm i ngx-qrcode-styling --save`
> 3. `ng serve  -o`
>    Báo lỗi: **self is not defined**
>    ![image](https://private-user-images.githubusercontent.com/22634754/336919490-0c6c53ed-3814-434c-a65b-8785640081d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTIxOTMsIm5iZiI6MTcxNzc1MTg5MywicGF0aCI6Ii8yMjYzNDc1NC8zMzY5MTk0OTAtMGM2YzUzZWQtMzgxNC00MzRjLWE2NWItODc4NTY0MDA4MWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA5MTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ODFkYzkwMGE2MmI3Y2JhNDhhYzkzMGMwMGE5MzE4ZjRjNDBjMzUwOWY2YzU5YjRiZWU1ZmE2MDk0YWFhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BGHoBKoZ4G0mM2ih75pn0kEFKnwLZ3-rV5zkjKZaCCo)

@GinCanhViet Bạn click vào 2 link này và chụp ảnh cho mình xem nhé. 
![image](https://github.com/id1945/ngx-qrcode-styling/assets/40824445/fef973c2-a380-4fd5-96b0-5bed3836e457)

**Comment by GinCanhViet** [comment]
@id1945 
![image](https://github.com/id1945/ngx-qrcode-styling/assets/22634754/bac6ba7b-0ef5-452f-be5e-69a3c3dd7ccf)

![image](https://github.com/id1945/ngx-qrcode-styling/assets/22634754/9c4edb56-e125-4381-8208-41cd97be6f52)

**Comment by GinCanhViet** [comment]
Dùng isPlatformBrowser để chắc chắn import khi chạy ở client thì ok
![image](https://github.com/id1945/ngx-qrcode-styling/assets/22634754/4ee6d050-6848-4e8f-b9f3-6f20aee8c709)

Cơ mà cũng ko có cách nào dùng đc

**Comment by GinCanhViet** [comment]
![image](https://github.com/id1945/ngx-qrcode-styling/assets/22634754/04605d43-d47b-4369-80b3-32f531e00ba7)


![image](https://github.com/id1945/ngx-qrcode-styling/assets/22634754/4c0b2bcf-747a-431c-9453-329a4d506e5d)

**Comment by GinCanhViet** [comment]
@id1945 Cảm ơn thời gian của bạn.
Hóa ra do mình lú thôi.

```
import('ngx-qrcode-styling').then(({ NgxQrcodeStylingService }) => {
  const qrCodeService = new NgxQrcodeStylingService();
  const config = ....;
  const container = document.getElementById('....');

  qrCodeService.create(config, container);
});
```
