### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by dodomui** [id1945/ngx-qrcode-styling#8]
"ngx-qrcode-styling": "^1.1.1",

```
import NgxQrcodeStylingModule
'NgxQrcodeStylingModule' does not appear to be an NgModule class.(-996002)

ngx-qrcode-styling.module.d.ts(1, 22): This likely means that the library (ngx-qrcode-styling) which declares NgxQrcodeStylingModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by id1945** [comment]
I understand this problem. I will be uploading a new version soon that allows IVY to work!

**Comment by id1945** [comment]
> "ngx-qrcode-styling": "^1.1.1",
> 
> ```
> import NgxQrcodeStylingModule
> 'NgxQrcodeStylingModule' does not appear to be an NgModule class.(-996002)
> 
> ngx-qrcode-styling.module.d.ts(1, 22): This likely means that the library (ngx-qrcode-styling) which declares NgxQrcodeStylingModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> ```

You could check again with v1.1.2!
